### Get /
GET http://localhost:5001

### Register /auth/register
POST  http://localhost:5001/auth/register
Content-Type: application/json

{
    "username" : "Mooo@gmail.com",
    "password" : "12345"

} 

### Login /auth/login
POST  http://localhost:5001/auth/login
Content-Type: application/json

{
    "username" : "Mooo@gmail.com",
    "password" : "12345"

} 